### ISSUE TITLE
Create custom Exceptions

### ISSUE THREAD

**Issue by faelperetta** [vrnsky/recipeper-server#3]
It's better create custom exceptions to you domain

Instead of thrown:
`new IllegalArgumentException("Recipe with given id not exists!")`

You could to do this
`new RecipeNotFoundExeption();`

In addition, the controller that handles the service that throws this kind of exceptions must return the proper HTTP code. If you thrown a RecipeNotFoundException your controller must return HTTP code 404 for the request

**Comment by vrnsky** [comment]
closed via #4
