### ISSUE TITLE
Разнести фронт и бек по разным проектам

### ISSUE THREAD

**Issue by vrnsky** [vrnsky/recipeper-server#9]
На данный момент фронт и бэк лежат в одном проекте. Из - за этого сборка проекта занимает довольно много времени.
Надо
* Разделить фронт и бэк на разные проекты

* В рамках этой задачи также переезжаем с maven на gradle
* Добавляем gradle release plugin

**Comment by zh-dmit** [comment]
знать бы что такое  gradle)

**Comment by vrnsky** [comment]
@zh-dmit почитай [здесь](https://golos.io/ru--obrazovanie/@brainburns-dev/zachem-nuzhny-sistemy-sborki-java-prilozhenii)

**Comment by vrnsky** [comment]
В сухом остатке:
* Фронт переехал [сюда](https://github.com/vrnsky/recipeper-front)
* В данном проекте полностью перешли на gradle
* Плагин включен, но на данный момент не работает.

**Comment by vrnsky** [comment]
На данный момент не получилось сделать инкрементальные релизы. Закрываем задачу и двигаемся дальше
